### ISSUE TITLE
Add CHANGELOG.md generation/update during release

### ISSUE THREAD

**Issue by asergeev-sc** [OpusCapita/filemanager#111]

**Comment by kvolkovich-sc** [comment]
> Is such CHANGELOG.md format will be OK?

# Change Log

## [v1.0.0-beta.8](https://github.com/OpusCapita/filemanager/tree/v1.0.0-beta.8) (2017-11-30)
[Full Changelog](https://github.com/OpusCapita/filemanager/compare/v1.0.0-beta.7...v1.0.0-beta.8)

**Merged pull requests:**

- Bug/normalize resource/\#109 [\#110](https://github.com/OpusCapita/filemanager/pull/110) ([abaliunov-sc](https://github.com/abaliunov-sc))

## [v1.0.0-beta.7](https://github.com/OpusCapita/filemanager/tree/v1.0.0-beta.7) (2017-11-28)
[Full Changelog](https://github.com/OpusCapita/filemanager/compare/v1.0.0-beta.5...v1.0.0-beta.7)

## [v1.0.0-beta.5](https://github.com/OpusCapita/filemanager/tree/v1.0.0-beta.5) (2017-11-27)
[Full Changelog](https://github.com/OpusCapita/filemanager/compare/v1.0.0-beta.4...v1.0.0-beta.5)

**Merged pull requests:**

- Create CODE\_OF\_CONDUCT.md [\#108](https://github.com/OpusCapita/filemanager/pull/108) ([kvolkovich-sc](https://github.com/kvolkovich-sc))

## [v1.0.0-beta.4](https://github.com/OpusCapita/filemanager/tree/v1.0.0-beta.4) (2017-11-20)
[Full Changelog](https://github.com/OpusCapita/filemanager/compare/v1.0.0-beta.3...v1.0.0-beta.4)

**Closed issues:**

- Add "FileManager" usage documentation \("client-react" and "server-nodejs"\) [\#81](https://github.com/OpusCapita/filemanager/issues/81)

**Merged pull requests:**

- Use "lerna" as a main build tool [\#107](https://github.com/OpusCapita/filemanager/pull/107) ([kvolkovich-sc](https://github.com/kvolkovich-sc))

## [v1.0.0-beta.3](https://github.com/OpusCapita/filemanager/tree/v1.0.0-beta.3) (2017-11-19)
[Full Changelog](https://github.com/OpusCapita/filemanager/compare/v0.0.1...v1.0.0-beta.3)

**Closed issues:**

- Prepare "filemanager" for initial release \(v1.0.0-beta.0\) [\#82](https://github.com/OpusCapita/filemanager/issues/82)

## [v0.0.1](https://github.com/OpusCapita/filemanager/tree/v0.0.1) (2017-11-17)
**Implemented enhancements:**

- Improve display API errors on client side [\#78](https://github.com/OpusCapita/filemanager/issues/78)
- Provide possibility to set initial path to folder for "nodejs\_v1" connector  [\#71](https://github.com/OpusCapita/filemanager/issues/71)
- Improve download file capability [\#66](https://github.com/OpusCapita/filemanager/issues/66)
- Implement "FileManager" react component [\#38](https://github.com/OpusCapita/filemanager/issues/38)
- Implement sorting for "server-nodejs" [\#35](https://github.com/OpusCapita/filemanager/issues/35)
- Implement sorting for "Google Drive API v2" [\#34](https://github.com/OpusCapita/filemanager/issues/34)
- Implement "row" and "files-view" contexts for "ContextMenu" [\#28](https://github.com/OpusCapita/filemanager/issues/28)

**Fixed bugs:**

- Message about uploading file with same name doesn't appear [\#89](https://github.com/OpusCapita/filemanager/issues/89)
- Context menu climbs on location bar [\#88](https://github.com/OpusCapita/filemanager/issues/88)
- Strange direction of arrows for sorting folder content [\#87](https://github.com/OpusCapita/filemanager/issues/87)
- Context menu is broken after downloading file in IE \(node.js v.1\) [\#85](https://github.com/OpusCapita/filemanager/issues/85)
- Disable ContextMenu appering by long left mouse down on not touch devices [\#67](https://github.com/OpusCapita/filemanager/issues/67)
- Fix - SetNameDialog submit on press "Enter" if value not specified and no input value changes [\#44](https://github.com/OpusCapita/filemanager/issues/44)
- Rename for "Google Drive API v2" don't check for existing file with same name [\#31](https://github.com/OpusCapita/filemanager/issues/31)
- Fix - wrong context menu items after pressing "Esc" key [\#23](https://github.com/OpusCapita/filemanager/issues/23)

**Closed issues:**

- Update RAML files for API [\#93](https://github.com/OpusCapita/filemanager/issues/93)
- Disable caching [\#75](https://github.com/OpusCapita/filemanager/issues/75)
- Add preview capability to file download [\#72](https://github.com/OpusCapita/filemanager/issues/72)
- Update mocha config to run tests using "webpack" instead of "babel" [\#63](https://github.com/OpusCapita/filemanager/issues/63)
- Make default L&F that fits “styles”: https://opuscapita.github.io/styles/demo/html/css.html [\#57](https://github.com/OpusCapita/filemanager/issues/57)
- Make different icons colors for different ListView item types [\#53](https://github.com/OpusCapita/filemanager/issues/53)
- Decrease font-size or/and font-weight for ListView items  [\#52](https://github.com/OpusCapita/filemanager/issues/52)
- React.PropTypes =\> 'prop-types' [\#50](https://github.com/OpusCapita/filemanager/issues/50)
- Fix build for IE11 [\#49](https://github.com/OpusCapita/filemanager/issues/49)
- Add progress indication for "Google Drive API v2" upload [\#48](https://github.com/OpusCapita/filemanager/issues/48)
- FileManager-scoped notification system for async events [\#43](https://github.com/OpusCapita/filemanager/issues/43)
- Implement "Toolbar" component [\#37](https://github.com/OpusCapita/filemanager/issues/37)
- Improve "capabilities" forceUpdate\(\) method by not appearing "loading-overlay" after each call [\#36](https://github.com/OpusCapita/filemanager/issues/36)
- Implement "upload single file" for "server-nodejs" [\#21](https://github.com/OpusCapita/filemanager/issues/21)
- Implement "upload single file" for "Google Drive API v2" [\#20](https://github.com/OpusCapita/filemanager/issues/20)
- Implement "remove files" for "server-nodejs v1" [\#18](https://github.com/OpusCapita/filemanager/issues/18)
- Implement "single file download" for "server-nodejs v1" [\#11](https://github.com/OpusCapita/filemanager/issues/11)
- Implement "create folder" for "server-nodejs v1" [\#9](https://github.com/OpusCapita/filemanager/issues/9)
- Implement "rename" for "server-nodejs v1" [\#8](https://github.com/OpusCapita/filemanager/issues/8)
- Implement "rename" for "Google Drive API v2" [\#7](https://github.com/OpusCapita/filemanager/issues/7)
- RAML files for API [\#5](https://github.com/OpusCapita/filemanager/issues/5)
- Implement basic server with node.js \(list folder content, download/upload/delete file, create/delete folder\) [\#3](https://github.com/OpusCapita/filemanager/issues/3)
- Implement client using React [\#2](https://github.com/OpusCapita/filemanager/issues/2)
- API documentation [\#1](https://github.com/OpusCapita/filemanager/issues/1)

**Merged pull requests:**

- Beta release/\#82 [\#106](https://github.com/OpusCapita/filemanager/pull/106) ([kvolkovich-sc](https://github.com/kvolkovich-sc))
- Validate raml/\#101 [\#105](https://github.com/OpusCapita/filemanager/pull/105) ([abaliunov-sc](https://github.com/abaliunov-sc))
- Validate raml/\#101 [\#104](https://github.com/OpusCapita/filemanager/pull/104) ([abaliunov-sc](https://github.com/abaliunov-sc))
- Validate raml/\#101 [\#102](https://github.com/OpusCapita/filemanager/pull/102) ([abaliunov-sc](https://github.com/abaliunov-sc))
- Update raml/\#93 [\#100](https://github.com/OpusCapita/filemanager/pull/100) ([abaliunov-sc](https://github.com/abaliunov-sc))
- Download context menu fix/85 [\#99](https://github.com/OpusCapita/filemanager/pull/99) ([estambakio-sc](https://github.com/estambakio-sc))
-  \#67 Disable ContextMenu appering by long left mouse down on not touch devices [\#95](https://github.com/OpusCapita/filemanager/pull/95) ([kvolkovich-sc](https://github.com/kvolkovich-sc))
-  \#88 Fix - Context menu climbs on location bar [\#94](https://github.com/OpusCapita/filemanager/pull/94) ([kvolkovich-sc](https://github.com/kvolkovich-sc))
- Proper sorting arrow direction \#87 [\#92](https://github.com/OpusCapita/filemanager/pull/92) ([estambakio-sc](https://github.com/estambakio-sc))
- Added error handling for getChildrenForId in node connector [\#91](https://github.com/OpusCapita/filemanager/pull/91) ([estambakio-sc](https://github.com/estambakio-sc))
- Initial path nodejs 2/\#71 [\#86](https://github.com/OpusCapita/filemanager/pull/86) ([abaliunov-sc](https://github.com/abaliunov-sc))
- Added error alerts for dl/upload/rename/createFolder/delete node capabilities [\#79](https://github.com/OpusCapita/filemanager/pull/79) ([estambakio-sc](https://github.com/estambakio-sc))
- Improve L'n'F, add sort for nodejs\_v1 connector [\#77](https://github.com/OpusCapita/filemanager/pull/77) ([kvolkovich-sc](https://github.com/kvolkovich-sc))
- Download handlers for google drive & node connectors. [\#76](https://github.com/OpusCapita/filemanager/pull/76) ([estambakio-sc](https://github.com/estambakio-sc))
- Remove and upload capabilities nodejs [\#74](https://github.com/OpusCapita/filemanager/pull/74) ([abaliunov-sc](https://github.com/abaliunov-sc))
- Preview capability in file download server API [\#73](https://github.com/OpusCapita/filemanager/pull/73) ([amourzenkov-sc](https://github.com/amourzenkov-sc))
- Implement different contexts for "ContextMenu" and "Toolbar" \(\#28\) [\#69](https://github.com/OpusCapita/filemanager/pull/69) ([kvolkovich-sc](https://github.com/kvolkovich-sc))
- Implement "Toolbar" component \(\#37\) [\#68](https://github.com/OpusCapita/filemanager/pull/68) ([kvolkovich-sc](https://github.com/kvolkovich-sc))
- Fix run mocha tests \( \#63 \) [\#65](https://github.com/OpusCapita/filemanager/pull/65) ([kvolkovich-sc](https://github.com/kvolkovich-sc))
- Implement sort by "title" and "modifiedDate" for Google Drive API v2 [\#64](https://github.com/OpusCapita/filemanager/pull/64) ([kvolkovich-sc](https://github.com/kvolkovich-sc))
- Migrated React.PropTypes =\> 'prop-types' \(\#50\) [\#62](https://github.com/OpusCapita/filemanager/pull/62) ([smoothpie](https://github.com/smoothpie))
- Rename, downolad, create folder for nodejs\_v1 API [\#59](https://github.com/OpusCapita/filemanager/pull/59) ([abaliunov-sc](https://github.com/abaliunov-sc))
- Notifications for upload to Google Drive \(\#48\) [\#58](https://github.com/OpusCapita/filemanager/pull/58) ([kvolkovich-sc](https://github.com/kvolkovich-sc))
-  \#49 Fix build for IE11 [\#51](https://github.com/OpusCapita/filemanager/pull/51) ([kvolkovich-sc](https://github.com/kvolkovich-sc))
- Implemented FileManager-scoped notification system for async events \(\#43\) [\#47](https://github.com/OpusCapita/filemanager/pull/47) ([kvolkovich-sc](https://github.com/kvolkovich-sc))
- Implement upload a single file to Google Drive API \(\#20\) [\#46](https://github.com/OpusCapita/filemanager/pull/46) ([kvolkovich-sc](https://github.com/kvolkovich-sc))
- Fix - SetNameDialog submit on press "Enter" if value not specified and no input value changes [\#45](https://github.com/OpusCapita/filemanager/pull/45) ([kvolkovich-sc](https://github.com/kvolkovich-sc))
- Fix - Rename for "Google Drive API v2" don't check for existing file with same name [\#33](https://github.com/OpusCapita/filemanager/pull/33) ([kvolkovich-sc](https://github.com/kvolkovich-sc))
- Rename capability gdrive/\#7 [\#27](https://github.com/OpusCapita/filemanager/pull/27) ([kvolkovich-sc](https://github.com/kvolkovich-sc))
- Basic server [\#26](https://github.com/OpusCapita/filemanager/pull/26) ([amourzenkov-sc](https://github.com/amourzenkov-sc))
- Raml/\#5 [\#6](https://github.com/OpusCapita/filemanager/pull/6) ([abaliunov-sc](https://github.com/abaliunov-sc))
- Implemented basic version of react file-manager client Ui/\#2 [\#4](https://github.com/OpusCapita/filemanager/pull/4) ([kvolkovich-sc](https://github.com/kvolkovich-sc))



\* *This Change Log was automatically generated by [github_changelog_generator](https://github.com/skywinder/Github-Changelog-Generator)*

**Comment by kvolkovich-sc** [comment]
Done. 

Custom sections support will be added after this [PR](https://github.com/skywinder/github-changelog-generator/pull/587) is approved. Its convenient for multiple npm packages within one repository  (checked on forked [repo](https://github.com/skywinder/github-changelog-generator) with this PR merged locally).
