### ISSUE TITLE
File filters/limits

### ISSUE THREAD

**Issue by uncaught** [OpusCapita/filemanager#207]
Is there any way to filter/limit the files that are uploaded and/or displayed?

E.g.:
- only allow certain file extensions to be uploaded to certain folders (or globally)
- hide all files starting with "."
- limit upload file size
- limit total disk usage for the fsRoot

**Comment by kvolkovich-sc** [comment]
- limit total disk usage for the fsRoot
  **NO** I think, this question is outside of this project scope.

Instead of add a lot of specific functionality and increase complexity of this package, I suggest you to fork "@opuscapita/react-filemanager-connector-node-v1" and implement it by yourself.

Show error notification if upload file name is invalid for you requirements. [Notification example](https://github.com/OpusCapita/filemanager/blob/1749a458787a90fcca327329fbeb7dd0ad1fec12/packages/connector-node-v1/src/capabilities/upload.js#L70).

Filter files you want to show:https://github.com/OpusCapita/filemanager/blob/1749a458787a90fcca327329fbeb7dd0ad1fec12/packages/connector-node-v1/src/api.js#L40 I you want to toggle it on UI, you can implement a [capablity](https://github.com/OpusCapita/filemanager/blob/master/packages/connector-google-drive-v2/src/capabilities).
