### ISSUE TITLE
How to customize the SetNameDialog?

### ISSUE THREAD

**Issue by Mengsuper** [OpusCapita/filemanager#215]
I want to customize the SetNameDialog for my usage. For example, I want to add another field "Subject" when user creates a new folder. Call anyone can tell me how to do that in a simple way? Thanks.

**Comment by kvolkovich-sc** [comment]
Hello, @Mengsuper!

I think you can do it only by forking `connector-node-v1`.

You can pass any React element here.

https://github.com/OpusCapita/filemanager/blob/30ab1c3a032452ae1d5a2b6ea424f7d182bc0f2e/packages/connector-node-v1/src/capabilities/create-folder.js#L70 

Instead of [rawDialogElement](https://github.com/OpusCapita/filemanager/blob/30ab1c3a032452ae1d5a2b6ea424f7d182bc0f2e/packages/connector-node-v1/src/capabilities/create-folder.js#L21), pass React Element instance.
