### ISSUE TITLE
Hiding or Disabling Toolbar Buttons

### ISSUE THREAD

**Issue by toddgeist** [OpusCapita/filemanager#245]
Is there a way to Hide or disable Toolbar buttons? In my case I need to disable upload and create folders, but allow Delete and Download.  Setting the readOnly flag to false on node server middleware is too broad. I need to disable individual buttons.

In attempt to make this work, I have forked the node-server to add a "transformer" that can intercept and transform the capabilities. Here I am trying to disable uploading or creating folders. So my config looks like this.
```
{
  fsRoot: fsRoot,
  rootName: "Saved Files",
  readOnly: false,
  transformer: items => {
    return items.map(item => {
      item.capabilities.canAddChildren = false;
        return item;
    });
  }
};
```
But this doesn't seem to work.

In my case I need to disable upload and create folders, but allow Delete and Download

Any ideas?

Thanks

**Comment by kvolkovich-sc** [comment]
Adding something like 'transformer' at server side is a good idea.

I think it don't work for you because you apply it for `listChildren`.

There are two calls on each changing of current directory:

- get info about current directory
- get info about current directory children

Just try to modify `getResource` function it this file:

https://github.com/OpusCapita/filemanager/blob/master/packages/server-nodejs/router/statResource.js

```js
'use strict';

const path = require('path');

const getClientIp = require('../utils/get-client-ip');
const { getResource } = require('./lib');

module.exports = ({
  config,
  req,
  res,
  handleError,
  path: userPath
}) => {
  config.logger.info(`Stat for ${path.join(config.fsRoot, userPath)} requested by ${getClientIp(req)}`);

  getResource({
    config,
    path: userPath
  }).
    then(resource => {
      let modifiedResource = ({
        ...resource,
        capabilities: ({
          ...resource.capabilities,
          canAddChildren: false
        })
      });

      return res.json(modifiedResource);
    }).
    catch(handleError);
};
```

Fast test shows that it works. `Add directory` and `Upload` buttons should be disabled.

**Comment by toddgeist** [comment]
ok, that is simpler..

I'll move my transformer to work there.

**Comment by imdkbj** [comment]
Hey, There should be public method for 

canListChildren: boolean
          canAddChildren: boolean
          canRemoveChildren: boolean
          canDelete: boolean
          canRename: boolean
          canCopy: boolean
          canEdit: boolean
          canDownload: boolean
