### ISSUE TITLE
Update lodash to 4.17.21

### ISSUE THREAD

**Issue by khomyakdi** [OpusCapita/filemanager#315]
Please update lodash to 4.17.21 because lodash versions prior to 4.17.21 are vulnerable to Command Injection via the template function [https://www.npmjs.com/advisories/1673](https://www.npmjs.com/advisories/1673)

**Comment by BilyachenkoOY** [comment]
Are there any particular reason to use fixed package version instead of allowing minor version to be different? This would allow to fix such issues per-project without need to await for a new release of filemanager.

**Comment by abaliunov-sc** [comment]
This particular reason is breaking changes, which may be in new versions of libraries. For this reason, we use fixed versions of libraries. And before upgrading the library version, we check how this version works in our code.

**Comment by BilyachenkoOY** [comment]
Do we expect breaking changes in minor version releases of library?

**Comment by estambakio-sc** [comment]
> Do we expect breaking changes in minor version releases of library?

I remember that previously it already happened once with `lodash.merge` function which started to work differently in a minor version upgrade of `lodash`, which led to a couple of days investigating why code stopped to work :). Since then we carefully update versions of JS libraries and test UIs on installations before merging such updates.

**Comment by estambakio-sc** [comment]
Closing as implemented in #317

**Comment by estambakio-sc** [comment]
Released in [1.1.9](https://github.com/OpusCapita/filemanager/releases/tag/v1.1.9)
